create a 1D array containing all even numbers between 10 and 100.

In [3]:
import numpy as np
a=np.arange(10,101,2)
print(a)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


create a 5*5 numpy array filled with multiple of 3.

In [33]:
a=np.arange(3,3*25+1,3).reshape(5,5)
a

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60],
       [63, 66, 69, 72, 75]])

In [35]:
a=np.arange(3,76,3).reshape(5,5)
a


array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60],
       [63, 66, 69, 72, 75]])

Generate a 4*4 matrix where the diagonal values are 1 and the rest are 0

In [36]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Create a 3D array of shape (2,3,4) filled with random integers from 0 to 20.

In [43]:
a=np.random.randint(0,20,size=(2,3,4))
a

array([[[10, 13, 10,  6],
        [ 1, 16, 17,  4],
        [17, 12,  2,  6]],

       [[17,  0, 17,  4],
        [13,  2, 12,  2],
        [18, 17,  0, 19]]], dtype=int32)

Reshape 1D array of 30 elements into shape (5,2,3) and print it's shape.

In [48]:
ar=np.arange(30).reshape(5,2,3)
print(ar)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


Create an array of 10 evenly spaced between 5 and 15

In [50]:
a1=np.linspace(5,15,10)
a1

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

Input list of numbers , find the second most highest element in the list.

In [ ]:
h=list(input("Enter value"))
k=[]
h.sort()
print(h)
print(h[n-1])

['1', '2', '3', '4', '6']


TypeError: unsupported operand type(s) for -: 'list' and 'int'