In [9]:
import numpy as np
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
b=a[::3]
b

array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
np.shares_memory(a,b)

True

In [12]:
b[4]=40
b

array([ 0,  3,  6,  9, 40, 15, 18])

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 40, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
a=np.arange(20)
c=a[::2].copy()
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
a=np.arange(20)
print(a)
b=a[::3]
print(b)
c=a[::2].copy()
print(c)
print(a,b,c)
b[4]=45
print(a,b,c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  3  6  9 12 15 18]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [ 0  3  6  9 12 15 18] [ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 45 13 14 15 16 17 18 19] [ 0  3  6  9 45 15 18] [ 0  2  4  6  8 10 12 14 16 18]


In [16]:
np.shares_memory(a,b)

True

In [17]:
c[5]=20
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 45, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
a=np.random.randint(0,20,3)
a

array([12, 18, 11], dtype=int32)

In [19]:
mask=(a%2==0)
mask

array([ True,  True, False])

In [20]:
print(a[mask])
print(a.dtype)

[12 18]
int32


In [21]:
a[mask]=-2   #-2 come at the place of 'True' 
a

array([-2, -2, 11], dtype=int32)

In [22]:
a=np.arange(0,100,20)
a

array([ 0, 20, 40, 60, 80])

In [23]:
a[[2,3]]  #returns values at the given index

array([40, 60])

In [24]:
a[[2,3]]=200,300
a                   #return values at two different index

array([  0,  20, 200, 300,  80])

In [25]:
a=np.array([2,3,4,5])
a+1000

array([1002, 1003, 1004, 1005])

In [26]:
a**200

array([                   0,  6627890308811632801,                    0,
       -7817535966050405663])

In [27]:
a=np.array([1,2,3,4])
b=np.array([10,40,20,40])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 42 23 44]
[ -9 -38 -17 -36]
[ 10  80  60 160]
[0.1  0.05 0.15 0.1 ]


In [28]:
b=np.ones(4)+10
print(b)

[11. 11. 11. 11.]


In [29]:
a - b

array([-10.,  -9.,  -8.,  -7.])

In [30]:
a*b

array([11., 22., 33., 44.])

In [31]:
c=np.diag([3,4,5,6])
print(c*c)
print(c.dot(c))

[[ 9  0  0  0]
 [ 0 16  0  0]
 [ 0  0 25  0]
 [ 0  0  0 36]]
[[ 9  0  0  0]
 [ 0 16  0  0]
 [ 0  0 25  0]
 [ 0  0  0 36]]


In [32]:
a=np.array([2,6,4,5])
b=np.array([5,6,7,8])
a==b

array([False,  True, False, False])

In [33]:
a>b

array([False, False, False, False])

In [34]:
a=np.array([3,4,5,6])
b=np.array([4,5,6,7])
c=np.array([3,4,5,6,])
np.array_equal(a,c)

True

In [35]:
np.array_equal(a,c)

True

In [36]:
a=np.array(([1,1,0,0]), dtype=bool)
b=np.array(([1,1,0,1]), dtype=bool)

np.logical_or(a,b)

array([ True,  True, False,  True])

In [87]:
np.logical_and(a,b)

array([ True,  True, False, False])

In [90]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [91]:
np.log(a)

C:\Users\Sinsinav505\AppData\Local\Temp\ipykernel_12112\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [92]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [95]:
a=np.arange(4)

a+np.array([1,2,3,4])

array([1, 3, 5, 7])

In [97]:
y=np.array([1,2,4,5])
np.sum(y)

np.int64(12)

In [104]:
y=np.array([[1,4,5],[2,3,6]])
y

array([[1, 4, 5],
       [2, 3, 6]])

In [105]:
y.sum(axis=0)

array([ 3,  7, 11])

In [106]:
y.sum(axis=1)

array([10, 11])

In [107]:
x=np.array([1,7,5])
y.min()

np.int64(1)

In [108]:
y.max()

np.int64(6)

In [109]:
y.argmin()

np.int64(0)

In [110]:
x.argmax()

np.int64(1)

In [112]:
np.all([True,True,True])

np.True_

In [113]:
np.any([True,False,True])

np.True_