Input list of numbers , find the second most highest element in the list.

In [ ]:
n=int(input("Enter the count in"))
h=[]
for i in range(n):
    a=int(input())
    h.append(a)
print(h)
max=0
ll=len(h)
for i in range(ll):
    if h[i]>max:
        max=h[i]
print(max)
print(h[-2])

In [ ]:
#second largest in a
n=int(input("Enter the no of elements:"))
l=[]
for i in range(n):
    l.append(int(input("Enter the number")))
print(l)
i=0
while(i!=len(l)):
    if l[i]>l[i+1]:
        t=l[i]
        l[i]=l[i+1]
        l[i+1]=t
    i=i+1
    if i == len(l)-1:
        break
print(l)
print(l[-1])
print(l[-2])

broadcasting


In [8]:
import numpy as np
a=np.array([[1,2,3,6],[2,4,5,6]])
b=np.array([2,2,3,1])
a+b

array([[3, 4, 6, 7],
       [4, 6, 8, 7]])

tile

In [34]:
b=np.tile(np.arange(0,20,10),(2,2)) 
print(b)   

[[ 0 10  0 10]
 [ 0 10  0 10]]


In [35]:
b=b.T
print(b)

[[ 0  0]
 [10 10]
 [ 0  0]
 [10 10]]


In [36]:
a=np.array([[5,6,7,8],[1,2,3,4]])
a

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [37]:
a=a.T
print(a)

[[5 1]
 [6 2]
 [7 3]
 [8 4]]


In [38]:
a+b

array([[ 5,  1],
       [16, 12],
       [ 7,  3],
       [18, 14]])

In [53]:
c=np.array([2,3,4,1,6])
c.shape


(5,)

In [54]:
c=c[ :,np.newaxis]
c.shape

(5, 1)

ravel

In [64]:
a=np.array([[2,3,4],[6,5,7],[7,8,2]])
a.ravel()

array([2, 3, 4, 6, 5, 7, 7, 8, 2])

In [65]:
a.T.ravel()

array([2, 6, 7, 3, 5, 8, 4, 7, 2])

In [66]:
a

array([[2, 3, 4],
       [6, 5, 7],
       [7, 8, 2]])

In [67]:
a[1,0]=400
a

array([[  2,   3,   4],
       [400,   5,   7],
       [  7,   8,   2]])

In [69]:
a=np.arange(5)
a.resize((8,8))
a

array([[0, 1, 2, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a=np.array([[4,5,1,2],[7,3,4,9]])
b=np.sort(a,axis=1) #row
b

array([[1, 2, 4, 5],
       [3, 4, 7, 9]])

In [73]:
a=np.array([[4,5,1,2],[7,3,4,9]])
b=np.sort(a,axis=0) #column
b

array([[4, 3, 1, 2],
       [7, 5, 4, 9]])

In [ ]:
a=np.array([4,8,2,5,1])  #returns the index of sorted numbers
b=np.argsort(a)
b

array([4, 2, 0, 3, 1])

In [75]:
a[b]

array([1, 2, 4, 5, 8])